# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\":\n\x15\x43heckInventoryRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"a\n\x16\x43heckInventoryResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\trequested\x18\x02 \x01(\x05\x12\x10\n\x08in_stock\x18\x03 \x01(\x05\x12\x11\n\tavailable\x18\x04 \x01(\x08\x32i\n\x10InventoryService\x12U\n\x0e\x43heckInventory\x12 .inventory.CheckInventoryRequest\x1a!.inventory.CheckInventoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKINVENTORYREQUEST']._serialized_start=30
  _globals['_CHECKINVENTORYREQUEST']._serialized_end=88
  _globals['_CHECKINVENTORYRESPONSE']._serialized_start=90
  _globals['_CHECKINVENTORYRESPONSE']._serialized_end=187
  _globals['_INVENTORYSERVICE']._serialized_start=189
  _globals['_INVENTORYSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
